# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/ui_files/BatchExtractWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWdw(object):
    def setupUi(self, MainWdw):
        MainWdw.setObjectName(_fromUtf8("MainWdw"))
        MainWdw.resize(673, 330)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWdw.sizePolicy().hasHeightForWidth())
        MainWdw.setSizePolicy(sizePolicy)
        MainWdw.setMinimumSize(QtCore.QSize(673, 330))
        MainWdw.setMaximumSize(QtCore.QSize(673, 330))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/other-python-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWdw.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWdw)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.testingFrame = QtGui.QFrame(self.centralwidget)
        self.testingFrame.setGeometry(QtCore.QRect(0, 0, 661, 351))
        self.testingFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.testingFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.testingFrame.setObjectName(_fromUtf8("testingFrame"))
        self.trainingFrame = QtGui.QFrame(self.centralwidget)
        self.trainingFrame.setEnabled(True)
        self.trainingFrame.setGeometry(QtCore.QRect(0, 0, 681, 421))
        self.trainingFrame.setWhatsThis(_fromUtf8(""))
        self.trainingFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.trainingFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.trainingFrame.setObjectName(_fromUtf8("trainingFrame"))
        self.featureExtGroup = QtGui.QGroupBox(self.trainingFrame)
        self.featureExtGroup.setGeometry(QtCore.QRect(10, 10, 651, 271))
        self.featureExtGroup.setObjectName(_fromUtf8("featureExtGroup"))
        self.openAudioBtn = QtGui.QPushButton(self.featureExtGroup)
        self.openAudioBtn.setGeometry(QtCore.QRect(10, 22, 101, 31))
        self.openAudioBtn.setObjectName(_fromUtf8("openAudioBtn"))
        self.extractSaveBtn = QtGui.QPushButton(self.featureExtGroup)
        self.extractSaveBtn.setGeometry(QtCore.QRect(10, 60, 101, 31))
        self.extractSaveBtn.setObjectName(_fromUtf8("extractSaveBtn"))
        self.featuresTbl = QtGui.QTableWidget(self.featureExtGroup)
        self.featuresTbl.setGeometry(QtCore.QRect(220, 10, 421, 251))
        self.featuresTbl.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.featuresTbl.setColumnCount(2)
        self.featuresTbl.setObjectName(_fromUtf8("featuresTbl"))
        self.featuresTbl.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.featuresTbl.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.featuresTbl.setHorizontalHeaderItem(1, item)
        self.featureExtLbl = QtGui.QLabel(self.featureExtGroup)
        self.featureExtLbl.setGeometry(QtCore.QRect(160, 10, 51, 16))
        self.featureExtLbl.setObjectName(_fromUtf8("featureExtLbl"))
        self.metaGroup = QtGui.QGroupBox(self.featureExtGroup)
        self.metaGroup.setGeometry(QtCore.QRect(10, 120, 201, 111))
        self.metaGroup.setObjectName(_fromUtf8("metaGroup"))
        self.fileLbl_2 = QtGui.QLabel(self.metaGroup)
        self.fileLbl_2.setGeometry(QtCore.QRect(10, 20, 71, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fileLbl_2.setFont(font)
        self.fileLbl_2.setObjectName(_fromUtf8("fileLbl_2"))
        self.progressLbl = QtGui.QLabel(self.metaGroup)
        self.progressLbl.setGeometry(QtCore.QRect(30, 80, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.progressLbl.setFont(font)
        self.progressLbl.setStyleSheet(_fromUtf8("color:red;"))
        self.progressLbl.setObjectName(_fromUtf8("progressLbl"))
        self.audioFilenameLbl = QtGui.QLabel(self.metaGroup)
        self.audioFilenameLbl.setGeometry(QtCore.QRect(70, 40, 121, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.audioFilenameLbl.setFont(font)
        self.audioFilenameLbl.setObjectName(_fromUtf8("audioFilenameLbl"))
        self.fileLbl = QtGui.QLabel(self.metaGroup)
        self.fileLbl.setGeometry(QtCore.QRect(10, 40, 51, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fileLbl.setFont(font)
        self.fileLbl.setObjectName(_fromUtf8("fileLbl"))
        self.fileLbl_3 = QtGui.QLabel(self.metaGroup)
        self.fileLbl_3.setGeometry(QtCore.QRect(10, 60, 81, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fileLbl_3.setFont(font)
        self.fileLbl_3.setObjectName(_fromUtf8("fileLbl_3"))
        self.audioFilenameLbl_3 = QtGui.QLabel(self.metaGroup)
        self.audioFilenameLbl_3.setGeometry(QtCore.QRect(70, 60, 101, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.audioFilenameLbl_3.setFont(font)
        self.audioFilenameLbl_3.setObjectName(_fromUtf8("audioFilenameLbl_3"))
        self.databaseNameVal = QtGui.QLineEdit(self.metaGroup)
        self.databaseNameVal.setGeometry(QtCore.QRect(80, 20, 113, 20))
        self.databaseNameVal.setObjectName(_fromUtf8("databaseNameVal"))
        self.progressBar = QtGui.QProgressBar(self.featureExtGroup)
        self.progressBar.setGeometry(QtCore.QRect(10, 240, 201, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.inclWordCheck = QtGui.QCheckBox(self.featureExtGroup)
        self.inclWordCheck.setGeometry(QtCore.QRect(120, 30, 101, 17))
        self.inclWordCheck.setChecked(True)
        self.inclWordCheck.setObjectName(_fromUtf8("inclWordCheck"))
        self.label = QtGui.QLabel(self.featureExtGroup)
        self.label.setGeometry(QtCore.QRect(120, 50, 81, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.frameSizeVal = QtGui.QComboBox(self.featureExtGroup)
        self.frameSizeVal.setGeometry(QtCore.QRect(120, 70, 81, 22))
        self.frameSizeVal.setObjectName(_fromUtf8("frameSizeVal"))
        self.frameSizeVal.addItem(_fromUtf8(""))
        self.frameSizeVal.addItem(_fromUtf8(""))
        self.frameSizeVal.addItem(_fromUtf8(""))
        self.shuffleBtn = QtGui.QPushButton(self.featureExtGroup)
        self.shuffleBtn.setGeometry(QtCore.QRect(130, 100, 75, 21))
        self.shuffleBtn.setObjectName(_fromUtf8("shuffleBtn"))
        MainWdw.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWdw)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWdw.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWdw)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWdw.setStatusBar(self.statusbar)
        self.actionTraining_Data = QtGui.QAction(MainWdw)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/data-data-recovery-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTraining_Data.setIcon(icon1)
        self.actionTraining_Data.setObjectName(_fromUtf8("actionTraining_Data"))
        self.actionTest_Data = QtGui.QAction(MainWdw)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/data-accept-database-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTest_Data.setIcon(icon2)
        self.actionTest_Data.setObjectName(_fromUtf8("actionTest_Data"))
        self.actionExit = QtGui.QAction(MainWdw)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/exit-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon3)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(MainWdw)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icon-why-dark.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon4)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionAbout_Qt = QtGui.QAction(MainWdw)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/qt.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_Qt.setIcon(icon5)
        self.actionAbout_Qt.setObjectName(_fromUtf8("actionAbout_Qt"))
        self.menuMenu.addAction(self.actionTraining_Data)
        self.menuMenu.addAction(self.actionTest_Data)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWdw)
        QtCore.QMetaObject.connectSlotsByName(MainWdw)

    def retranslateUi(self, MainWdw):
        MainWdw.setWindowTitle(_translate("MainWdw", "Text Dependent Speaker Verification - Training", None))
        self.featureExtGroup.setTitle(_translate("MainWdw", "Batch Feature Extraction", None))
        self.openAudioBtn.setText(_translate("MainWdw", "Open Audio Files", None))
        self.extractSaveBtn.setText(_translate("MainWdw", "Extract && Save", None))
        item = self.featuresTbl.horizontalHeaderItem(0)
        item.setText(_translate("MainWdw", "File", None))
        item = self.featuresTbl.horizontalHeaderItem(1)
        item.setText(_translate("MainWdw", "Output Class", None))
        self.featureExtLbl.setText(_translate("MainWdw", "Features : ", None))
        self.metaGroup.setTitle(_translate("MainWdw", "Meta Info", None))
        self.fileLbl_2.setText(_translate("MainWdw", "Database    :", None))
        self.progressLbl.setText(_translate("MainWdw", "PLEASE WAIT", None))
        self.audioFilenameLbl.setText(_translate("MainWdw", ":", None))
        self.fileLbl.setText(_translate("MainWdw", "Total Files", None))
        self.fileLbl_3.setText(_translate("MainWdw", "Processed", None))
        self.audioFilenameLbl_3.setText(_translate("MainWdw", ":", None))
        self.inclWordCheck.setText(_translate("MainWdw", "Include Word", None))
        self.label.setText(_translate("MainWdw", "Frame Size :", None))
        self.frameSizeVal.setItemText(0, _translate("MainWdw", "128", None))
        self.frameSizeVal.setItemText(1, _translate("MainWdw", "256", None))
        self.frameSizeVal.setItemText(2, _translate("MainWdw", "512", None))
        self.shuffleBtn.setText(_translate("MainWdw", "Shuffle", None))
        self.menuMenu.setTitle(_translate("MainWdw", "Menu", None))
        self.menuAbout.setTitle(_translate("MainWdw", "Help", None))
        self.actionTraining_Data.setText(_translate("MainWdw", "Training Data", None))
        self.actionTest_Data.setText(_translate("MainWdw", "Testing Data", None))
        self.actionExit.setText(_translate("MainWdw", "Exit", None))
        self.actionAbout.setText(_translate("MainWdw", "About", None))
        self.actionAbout_Qt.setText(_translate("MainWdw", "About Qt", None))

import image_set_rc
