# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/ui_files/BatchTestWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWdw(object):
    def setupUi(self, MainWdw):
        MainWdw.setObjectName(_fromUtf8("MainWdw"))
        MainWdw.resize(673, 365)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWdw.sizePolicy().hasHeightForWidth())
        MainWdw.setSizePolicy(sizePolicy)
        MainWdw.setMinimumSize(QtCore.QSize(673, 306))
        MainWdw.setMaximumSize(QtCore.QSize(673, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/other-python-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWdw.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWdw)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.testingFrame = QtGui.QFrame(self.centralwidget)
        self.testingFrame.setGeometry(QtCore.QRect(0, 0, 661, 351))
        self.testingFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.testingFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.testingFrame.setObjectName(_fromUtf8("testingFrame"))
        self.trainingFrame = QtGui.QFrame(self.centralwidget)
        self.trainingFrame.setEnabled(True)
        self.trainingFrame.setGeometry(QtCore.QRect(0, 0, 681, 421))
        self.trainingFrame.setWhatsThis(_fromUtf8(""))
        self.trainingFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.trainingFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.trainingFrame.setObjectName(_fromUtf8("trainingFrame"))
        self.testGroup = QtGui.QGroupBox(self.trainingFrame)
        self.testGroup.setGeometry(QtCore.QRect(10, 10, 651, 311))
        self.testGroup.setObjectName(_fromUtf8("testGroup"))
        self.openAudioBtn = QtGui.QPushButton(self.testGroup)
        self.openAudioBtn.setGeometry(QtCore.QRect(10, 22, 101, 31))
        self.openAudioBtn.setObjectName(_fromUtf8("openAudioBtn"))
        self.startTestBtn = QtGui.QPushButton(self.testGroup)
        self.startTestBtn.setGeometry(QtCore.QRect(10, 60, 101, 31))
        self.startTestBtn.setObjectName(_fromUtf8("startTestBtn"))
        self.featuresTbl = QtGui.QTableWidget(self.testGroup)
        self.featuresTbl.setGeometry(QtCore.QRect(220, 10, 421, 261))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.featuresTbl.setFont(font)
        self.featuresTbl.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.featuresTbl.setColumnCount(5)
        self.featuresTbl.setObjectName(_fromUtf8("featuresTbl"))
        self.featuresTbl.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.featuresTbl.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.featuresTbl.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.featuresTbl.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.featuresTbl.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.featuresTbl.setHorizontalHeaderItem(4, item)
        self.metaGroup = QtGui.QGroupBox(self.testGroup)
        self.metaGroup.setGeometry(QtCore.QRect(10, 160, 201, 111))
        self.metaGroup.setObjectName(_fromUtf8("metaGroup"))
        self.progressLbl = QtGui.QLabel(self.metaGroup)
        self.progressLbl.setGeometry(QtCore.QRect(30, 80, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.progressLbl.setFont(font)
        self.progressLbl.setStyleSheet(_fromUtf8("color:red;"))
        self.progressLbl.setObjectName(_fromUtf8("progressLbl"))
        self.audioFilenameLbl = QtGui.QLabel(self.metaGroup)
        self.audioFilenameLbl.setGeometry(QtCore.QRect(70, 20, 121, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.audioFilenameLbl.setFont(font)
        self.audioFilenameLbl.setObjectName(_fromUtf8("audioFilenameLbl"))
        self.fileLbl = QtGui.QLabel(self.metaGroup)
        self.fileLbl.setGeometry(QtCore.QRect(10, 20, 51, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fileLbl.setFont(font)
        self.fileLbl.setObjectName(_fromUtf8("fileLbl"))
        self.fileLbl_3 = QtGui.QLabel(self.metaGroup)
        self.fileLbl_3.setGeometry(QtCore.QRect(10, 40, 81, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fileLbl_3.setFont(font)
        self.fileLbl_3.setObjectName(_fromUtf8("fileLbl_3"))
        self.audioFilenameLbl_3 = QtGui.QLabel(self.metaGroup)
        self.audioFilenameLbl_3.setGeometry(QtCore.QRect(70, 40, 101, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.audioFilenameLbl_3.setFont(font)
        self.audioFilenameLbl_3.setObjectName(_fromUtf8("audioFilenameLbl_3"))
        self.progressBar = QtGui.QProgressBar(self.testGroup)
        self.progressBar.setGeometry(QtCore.QRect(10, 280, 201, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.label = QtGui.QLabel(self.testGroup)
        self.label.setGeometry(QtCore.QRect(120, 20, 81, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.frameSizeVal = QtGui.QComboBox(self.testGroup)
        self.frameSizeVal.setGeometry(QtCore.QRect(120, 40, 81, 22))
        self.frameSizeVal.setObjectName(_fromUtf8("frameSizeVal"))
        self.frameSizeVal.addItem(_fromUtf8(""))
        self.frameSizeVal.addItem(_fromUtf8(""))
        self.frameSizeVal.addItem(_fromUtf8(""))
        self.exportCSVBtn = QtGui.QPushButton(self.testGroup)
        self.exportCSVBtn.setGeometry(QtCore.QRect(554, 280, 81, 23))
        self.exportCSVBtn.setObjectName(_fromUtf8("exportCSVBtn"))
        self.accuracyLbl = QtGui.QLabel(self.testGroup)
        self.accuracyLbl.setGeometry(QtCore.QRect(230, 280, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.accuracyLbl.setFont(font)
        self.accuracyLbl.setObjectName(_fromUtf8("accuracyLbl"))
        self.accuracyVal = QtGui.QLabel(self.testGroup)
        self.accuracyVal.setGeometry(QtCore.QRect(360, 280, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.accuracyVal.setFont(font)
        self.accuracyVal.setText(_fromUtf8(""))
        self.accuracyVal.setObjectName(_fromUtf8("accuracyVal"))
        self.iterLbl_2 = QtGui.QLabel(self.testGroup)
        self.iterLbl_2.setGeometry(QtCore.QRect(10, 100, 61, 16))
        self.iterLbl_2.setObjectName(_fromUtf8("iterLbl_2"))
        self.databaseSelect = QtGui.QComboBox(self.testGroup)
        self.databaseSelect.setGeometry(QtCore.QRect(10, 120, 201, 20))
        self.databaseSelect.setObjectName(_fromUtf8("databaseSelect"))
        self.clrFilesBtn = QtGui.QPushButton(self.testGroup)
        self.clrFilesBtn.setGeometry(QtCore.QRect(140, 90, 75, 23))
        self.clrFilesBtn.setObjectName(_fromUtf8("clrFilesBtn"))
        self.reloadDatabaseBtn = QtGui.QPushButton(self.testGroup)
        self.reloadDatabaseBtn.setGeometry(QtCore.QRect(70, 100, 21, 16))
        self.reloadDatabaseBtn.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/1462919668_Update.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reloadDatabaseBtn.setIcon(icon1)
        self.reloadDatabaseBtn.setIconSize(QtCore.QSize(12, 12))
        self.reloadDatabaseBtn.setObjectName(_fromUtf8("reloadDatabaseBtn"))
        MainWdw.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWdw)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWdw.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWdw)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWdw.setStatusBar(self.statusbar)
        self.actionTraining_Data = QtGui.QAction(MainWdw)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/data-data-recovery-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTraining_Data.setIcon(icon2)
        self.actionTraining_Data.setObjectName(_fromUtf8("actionTraining_Data"))
        self.actionTest_Data = QtGui.QAction(MainWdw)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/data-accept-database-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTest_Data.setIcon(icon3)
        self.actionTest_Data.setObjectName(_fromUtf8("actionTest_Data"))
        self.actionExit = QtGui.QAction(MainWdw)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/exit-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(MainWdw)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icon-why-dark.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon5)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionAbout_Qt = QtGui.QAction(MainWdw)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/qt.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_Qt.setIcon(icon6)
        self.actionAbout_Qt.setObjectName(_fromUtf8("actionAbout_Qt"))
        self.menuMenu.addAction(self.actionTraining_Data)
        self.menuMenu.addAction(self.actionTest_Data)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWdw)
        QtCore.QMetaObject.connectSlotsByName(MainWdw)

    def retranslateUi(self, MainWdw):
        MainWdw.setWindowTitle(_translate("MainWdw", "Text Dependent Speaker Verification - Training", None))
        self.testGroup.setTitle(_translate("MainWdw", "Batch Testing", None))
        self.openAudioBtn.setText(_translate("MainWdw", "Open Audio Files", None))
        self.startTestBtn.setText(_translate("MainWdw", "Start Testing", None))
        item = self.featuresTbl.horizontalHeaderItem(0)
        item.setText(_translate("MainWdw", "Expected Speaker", None))
        item = self.featuresTbl.horizontalHeaderItem(1)
        item.setText(_translate("MainWdw", "Expected Word", None))
        item = self.featuresTbl.horizontalHeaderItem(2)
        item.setText(_translate("MainWdw", "Output Speaker", None))
        item = self.featuresTbl.horizontalHeaderItem(3)
        item.setText(_translate("MainWdw", "Output Word", None))
        item = self.featuresTbl.horizontalHeaderItem(4)
        item.setText(_translate("MainWdw", "Result", None))
        self.metaGroup.setTitle(_translate("MainWdw", "Meta Info", None))
        self.progressLbl.setText(_translate("MainWdw", "PLEASE WAIT", None))
        self.audioFilenameLbl.setText(_translate("MainWdw", ":", None))
        self.fileLbl.setText(_translate("MainWdw", "Total Files", None))
        self.fileLbl_3.setText(_translate("MainWdw", "Processed", None))
        self.audioFilenameLbl_3.setText(_translate("MainWdw", ":", None))
        self.label.setText(_translate("MainWdw", "Frame Size :", None))
        self.frameSizeVal.setItemText(0, _translate("MainWdw", "128", None))
        self.frameSizeVal.setItemText(1, _translate("MainWdw", "256", None))
        self.frameSizeVal.setItemText(2, _translate("MainWdw", "512", None))
        self.exportCSVBtn.setText(_translate("MainWdw", "Export to CSV", None))
        self.accuracyLbl.setText(_translate("MainWdw", "Identification Rate :", None))
        self.iterLbl_2.setText(_translate("MainWdw", "Database : ", None))
        self.clrFilesBtn.setText(_translate("MainWdw", "Clear All", None))
        self.menuMenu.setTitle(_translate("MainWdw", "Menu", None))
        self.menuAbout.setTitle(_translate("MainWdw", "Help", None))
        self.actionTraining_Data.setText(_translate("MainWdw", "Training Data", None))
        self.actionTest_Data.setText(_translate("MainWdw", "Testing Data", None))
        self.actionExit.setText(_translate("MainWdw", "Exit", None))
        self.actionAbout.setText(_translate("MainWdw", "About", None))
        self.actionAbout_Qt.setText(_translate("MainWdw", "About Qt", None))

import image_set_rc
