# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/ui_files/TestWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TestWdw(object):
    def setupUi(self, TestWdw):
        TestWdw.setObjectName(_fromUtf8("TestWdw"))
        TestWdw.resize(689, 547)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TestWdw.sizePolicy().hasHeightForWidth())
        TestWdw.setSizePolicy(sizePolicy)
        TestWdw.setMinimumSize(QtCore.QSize(689, 547))
        TestWdw.setMaximumSize(QtCore.QSize(689, 547))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/other-python-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TestWdw.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(TestWdw)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.testingFrame = QtGui.QFrame(self.centralwidget)
        self.testingFrame.setGeometry(QtCore.QRect(0, 0, 661, 351))
        self.testingFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.testingFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.testingFrame.setObjectName(_fromUtf8("testingFrame"))
        self.trainingFrame = QtGui.QFrame(self.centralwidget)
        self.trainingFrame.setEnabled(True)
        self.trainingFrame.setGeometry(QtCore.QRect(0, 0, 701, 511))
        self.trainingFrame.setWhatsThis(_fromUtf8(""))
        self.trainingFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.trainingFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.trainingFrame.setObjectName(_fromUtf8("trainingFrame"))
        self.featureExtGroup = QtGui.QGroupBox(self.trainingFrame)
        self.featureExtGroup.setGeometry(QtCore.QRect(10, 10, 671, 181))
        self.featureExtGroup.setObjectName(_fromUtf8("featureExtGroup"))
        self.openAudioBtn = QtGui.QPushButton(self.featureExtGroup)
        self.openAudioBtn.setGeometry(QtCore.QRect(10, 22, 91, 31))
        self.openAudioBtn.setObjectName(_fromUtf8("openAudioBtn"))
        self.extractSaveBtn = QtGui.QPushButton(self.featureExtGroup)
        self.extractSaveBtn.setGeometry(QtCore.QRect(540, 10, 121, 41))
        self.extractSaveBtn.setObjectName(_fromUtf8("extractSaveBtn"))
        self.featuresTbl = QtGui.QTableWidget(self.featureExtGroup)
        self.featuresTbl.setGeometry(QtCore.QRect(240, 80, 421, 91))
        self.featuresTbl.setObjectName(_fromUtf8("featuresTbl"))
        self.featuresTbl.setColumnCount(0)
        self.featuresTbl.setRowCount(0)
        self.featureExtLbl = QtGui.QLabel(self.featureExtGroup)
        self.featureExtLbl.setGeometry(QtCore.QRect(610, 60, 51, 16))
        self.featureExtLbl.setObjectName(_fromUtf8("featureExtLbl"))
        self.seekSlider = phonon.Phonon.SeekSlider(self.featureExtGroup)
        self.seekSlider.setGeometry(QtCore.QRect(120, 20, 161, 16))
        self.seekSlider.setObjectName(_fromUtf8("seekSlider"))
        self.lcdNumber = QtGui.QLCDNumber(self.featureExtGroup)
        self.lcdNumber.setGeometry(QtCore.QRect(290, 20, 64, 21))
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.volumeSlider = phonon.Phonon.VolumeSlider(self.featureExtGroup)
        self.volumeSlider.setGeometry(QtCore.QRect(240, 50, 109, 16))
        self.volumeSlider.setObjectName(_fromUtf8("volumeSlider"))
        self.audioPlayBtn = QtGui.QPushButton(self.featureExtGroup)
        self.audioPlayBtn.setGeometry(QtCore.QRect(120, 40, 41, 31))
        self.audioPlayBtn.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/1461587404_play-arrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.audioPlayBtn.setIcon(icon1)
        self.audioPlayBtn.setIconSize(QtCore.QSize(16, 16))
        self.audioPlayBtn.setFlat(False)
        self.audioPlayBtn.setObjectName(_fromUtf8("audioPlayBtn"))
        self.audioPauseBtn = QtGui.QPushButton(self.featureExtGroup)
        self.audioPauseBtn.setGeometry(QtCore.QRect(160, 40, 41, 31))
        self.audioPauseBtn.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/1461587409_Pause_Icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.audioPauseBtn.setIcon(icon2)
        self.audioPauseBtn.setIconSize(QtCore.QSize(22, 22))
        self.audioPauseBtn.setObjectName(_fromUtf8("audioPauseBtn"))
        self.audioStopBtn = QtGui.QPushButton(self.featureExtGroup)
        self.audioStopBtn.setGeometry(QtCore.QRect(200, 40, 41, 31))
        self.audioStopBtn.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/1461587394_black_4_audio_stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.audioStopBtn.setIcon(icon3)
        self.audioStopBtn.setObjectName(_fromUtf8("audioStopBtn"))
        self.metaGroup = QtGui.QGroupBox(self.featureExtGroup)
        self.metaGroup.setGeometry(QtCore.QRect(10, 80, 221, 91))
        self.metaGroup.setObjectName(_fromUtf8("metaGroup"))
        self.fileLbl = QtGui.QLabel(self.metaGroup)
        self.fileLbl.setGeometry(QtCore.QRect(10, 20, 31, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fileLbl.setFont(font)
        self.fileLbl.setObjectName(_fromUtf8("fileLbl"))
        self.samplesLbl = QtGui.QLabel(self.metaGroup)
        self.samplesLbl.setGeometry(QtCore.QRect(10, 40, 51, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.samplesLbl.setFont(font)
        self.samplesLbl.setObjectName(_fromUtf8("samplesLbl"))
        self.fsLbl = QtGui.QLabel(self.metaGroup)
        self.fsLbl.setGeometry(QtCore.QRect(10, 60, 21, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fsLbl.setFont(font)
        self.fsLbl.setObjectName(_fromUtf8("fsLbl"))
        self.audioFilenameLbl = QtGui.QLabel(self.metaGroup)
        self.audioFilenameLbl.setGeometry(QtCore.QRect(60, 20, 131, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.audioFilenameLbl.setFont(font)
        self.audioFilenameLbl.setObjectName(_fromUtf8("audioFilenameLbl"))
        self.sampleValLbl = QtGui.QLabel(self.metaGroup)
        self.sampleValLbl.setGeometry(QtCore.QRect(60, 40, 131, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sampleValLbl.setFont(font)
        self.sampleValLbl.setObjectName(_fromUtf8("sampleValLbl"))
        self.fsValLbl = QtGui.QLabel(self.metaGroup)
        self.fsValLbl.setGeometry(QtCore.QRect(60, 60, 131, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fsValLbl.setFont(font)
        self.fsValLbl.setObjectName(_fromUtf8("fsValLbl"))
        self.testDataGroup = QtGui.QGroupBox(self.trainingFrame)
        self.testDataGroup.setGeometry(QtCore.QRect(10, 200, 671, 301))
        self.testDataGroup.setObjectName(_fromUtf8("testDataGroup"))
        self.testDataTab = QtGui.QTabWidget(self.testDataGroup)
        self.testDataTab.setGeometry(QtCore.QRect(180, 20, 481, 271))
        self.testDataTab.setObjectName(_fromUtf8("testDataTab"))
        self.origSignalTab = QtGui.QWidget()
        self.origSignalTab.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.origSignalTab.setFont(font)
        self.origSignalTab.setObjectName(_fromUtf8("origSignalTab"))
        self.originalPlot = QtGui.QWidget(self.origSignalTab)
        self.originalPlot.setGeometry(QtCore.QRect(0, 0, 481, 251))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.originalPlot.sizePolicy().hasHeightForWidth())
        self.originalPlot.setSizePolicy(sizePolicy)
        self.originalPlot.setObjectName(_fromUtf8("originalPlot"))
        self.originalPlotLyt = QtGui.QVBoxLayout(self.originalPlot)
        self.originalPlotLyt.setObjectName(_fromUtf8("originalPlotLyt"))
        self.testDataTab.addTab(self.origSignalTab, _fromUtf8(""))
        self.framedSgnlTab = QtGui.QWidget()
        self.framedSgnlTab.setObjectName(_fromUtf8("framedSgnlTab"))
        self.framedPlot = QtGui.QWidget(self.framedSgnlTab)
        self.framedPlot.setGeometry(QtCore.QRect(0, 0, 481, 251))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framedPlot.sizePolicy().hasHeightForWidth())
        self.framedPlot.setSizePolicy(sizePolicy)
        self.framedPlot.setObjectName(_fromUtf8("framedPlot"))
        self.framedPlotLyt = QtGui.QVBoxLayout(self.framedPlot)
        self.framedPlotLyt.setObjectName(_fromUtf8("framedPlotLyt"))
        self.testDataTab.addTab(self.framedSgnlTab, _fromUtf8(""))
        self.wdwSignalTab = QtGui.QWidget()
        self.wdwSignalTab.setObjectName(_fromUtf8("wdwSignalTab"))
        self.framedPlot_2 = QtGui.QWidget(self.wdwSignalTab)
        self.framedPlot_2.setGeometry(QtCore.QRect(0, 0, 481, 251))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framedPlot_2.sizePolicy().hasHeightForWidth())
        self.framedPlot_2.setSizePolicy(sizePolicy)
        self.framedPlot_2.setObjectName(_fromUtf8("framedPlot_2"))
        self.windowedPlotLyt = QtGui.QVBoxLayout(self.framedPlot_2)
        self.windowedPlotLyt.setObjectName(_fromUtf8("windowedPlotLyt"))
        self.testDataTab.addTab(self.wdwSignalTab, _fromUtf8(""))
        self.fftTab = QtGui.QWidget()
        self.fftTab.setObjectName(_fromUtf8("fftTab"))
        self.framedPlot_3 = QtGui.QWidget(self.fftTab)
        self.framedPlot_3.setGeometry(QtCore.QRect(0, 0, 481, 251))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framedPlot_3.sizePolicy().hasHeightForWidth())
        self.framedPlot_3.setSizePolicy(sizePolicy)
        self.framedPlot_3.setObjectName(_fromUtf8("framedPlot_3"))
        self.fftPloyLyt = QtGui.QVBoxLayout(self.framedPlot_3)
        self.fftPloyLyt.setObjectName(_fromUtf8("fftPloyLyt"))
        self.testDataTab.addTab(self.fftTab, _fromUtf8(""))
        self.melWrapTab = QtGui.QWidget()
        self.melWrapTab.setObjectName(_fromUtf8("melWrapTab"))
        self.framedPlot_4 = QtGui.QWidget(self.melWrapTab)
        self.framedPlot_4.setGeometry(QtCore.QRect(0, 0, 481, 251))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framedPlot_4.sizePolicy().hasHeightForWidth())
        self.framedPlot_4.setSizePolicy(sizePolicy)
        self.framedPlot_4.setObjectName(_fromUtf8("framedPlot_4"))
        self.melPlotLyt = QtGui.QVBoxLayout(self.framedPlot_4)
        self.melPlotLyt.setObjectName(_fromUtf8("melPlotLyt"))
        self.testDataTab.addTab(self.melWrapTab, _fromUtf8(""))
        self.mfccTab = QtGui.QWidget()
        self.mfccTab.setObjectName(_fromUtf8("mfccTab"))
        self.framedPlot_5 = QtGui.QWidget(self.mfccTab)
        self.framedPlot_5.setGeometry(QtCore.QRect(0, 0, 481, 251))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framedPlot_5.sizePolicy().hasHeightForWidth())
        self.framedPlot_5.setSizePolicy(sizePolicy)
        self.framedPlot_5.setObjectName(_fromUtf8("framedPlot_5"))
        self.mfccPlotLyt = QtGui.QVBoxLayout(self.framedPlot_5)
        self.mfccPlotLyt.setObjectName(_fromUtf8("mfccPlotLyt"))
        self.testDataTab.addTab(self.mfccTab, _fromUtf8(""))
        self.paramsGroup = QtGui.QGroupBox(self.testDataGroup)
        self.paramsGroup.setGeometry(QtCore.QRect(10, 20, 161, 111))
        self.paramsGroup.setObjectName(_fromUtf8("paramsGroup"))
        self.learningRLbl = QtGui.QLabel(self.paramsGroup)
        self.learningRLbl.setGeometry(QtCore.QRect(10, 20, 31, 16))
        self.learningRLbl.setObjectName(_fromUtf8("learningRLbl"))
        self.learningRDecrLbl = QtGui.QLabel(self.paramsGroup)
        self.learningRDecrLbl.setGeometry(QtCore.QRect(10, 40, 51, 16))
        self.learningRDecrLbl.setObjectName(_fromUtf8("learningRDecrLbl"))
        self.iterLbl = QtGui.QLabel(self.paramsGroup)
        self.iterLbl.setGeometry(QtCore.QRect(10, 60, 51, 16))
        self.iterLbl.setObjectName(_fromUtf8("iterLbl"))
        self.learningRVal = QtGui.QDoubleSpinBox(self.paramsGroup)
        self.learningRVal.setGeometry(QtCore.QRect(70, 20, 62, 16))
        self.learningRVal.setFrame(False)
        self.learningRVal.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.learningRVal.setDecimals(3)
        self.learningRVal.setMaximum(9999.999)
        self.learningRVal.setSingleStep(0.01)
        self.learningRVal.setObjectName(_fromUtf8("learningRVal"))
        self.learningRDecrVal = QtGui.QDoubleSpinBox(self.paramsGroup)
        self.learningRDecrVal.setGeometry(QtCore.QRect(70, 40, 62, 16))
        self.learningRDecrVal.setFrame(False)
        self.learningRDecrVal.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.learningRDecrVal.setDecimals(3)
        self.learningRDecrVal.setMaximum(9999.999)
        self.learningRDecrVal.setSingleStep(0.001)
        self.learningRDecrVal.setObjectName(_fromUtf8("learningRDecrVal"))
        self.iterVal = QtGui.QSpinBox(self.paramsGroup)
        self.iterVal.setGeometry(QtCore.QRect(70, 60, 61, 16))
        self.iterVal.setFrame(False)
        self.iterVal.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.iterVal.setMaximum(9999)
        self.iterVal.setObjectName(_fromUtf8("iterVal"))
        self.testProgress = QtGui.QProgressBar(self.testDataGroup)
        self.testProgress.setGeometry(QtCore.QRect(10, 270, 161, 23))
        self.testProgress.setProperty("value", 0)
        self.testProgress.setTextVisible(False)
        self.testProgress.setOrientation(QtCore.Qt.Horizontal)
        self.testProgress.setInvertedAppearance(False)
        self.testProgress.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.testProgress.setObjectName(_fromUtf8("testProgress"))
        self.identifyBtn = QtGui.QPushButton(self.testDataGroup)
        self.identifyBtn.setGeometry(QtCore.QRect(10, 140, 161, 51))
        self.identifyBtn.setObjectName(_fromUtf8("identifyBtn"))
        self.wordVal = QtGui.QLabel(self.testDataGroup)
        self.wordVal.setGeometry(QtCore.QRect(60, 220, 111, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.wordVal.setFont(font)
        self.wordVal.setObjectName(_fromUtf8("wordVal"))
        self.wordLbl = QtGui.QLabel(self.testDataGroup)
        self.wordLbl.setGeometry(QtCore.QRect(10, 220, 51, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.wordLbl.setFont(font)
        self.wordLbl.setObjectName(_fromUtf8("wordLbl"))
        self.speakerVal = QtGui.QLabel(self.testDataGroup)
        self.speakerVal.setGeometry(QtCore.QRect(60, 200, 111, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.speakerVal.setFont(font)
        self.speakerVal.setObjectName(_fromUtf8("speakerVal"))
        self.speakerLbl = QtGui.QLabel(self.testDataGroup)
        self.speakerLbl.setGeometry(QtCore.QRect(10, 200, 41, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.speakerLbl.setFont(font)
        self.speakerLbl.setObjectName(_fromUtf8("speakerLbl"))
        self.resultLbl = QtGui.QLabel(self.testDataGroup)
        self.resultLbl.setGeometry(QtCore.QRect(10, 240, 151, 21))
        self.resultLbl.setMaximumSize(QtCore.QSize(16777215, 16777214))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.resultLbl.setFont(font)
        self.resultLbl.setStyleSheet(_fromUtf8("color: rgb(53, 223, 34)"))
        self.resultLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.resultLbl.setObjectName(_fromUtf8("resultLbl"))
        TestWdw.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(TestWdw)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 689, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        TestWdw.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(TestWdw)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        TestWdw.setStatusBar(self.statusbar)
        self.actionTraining_Data = QtGui.QAction(TestWdw)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/data-data-recovery-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTraining_Data.setIcon(icon4)
        self.actionTraining_Data.setObjectName(_fromUtf8("actionTraining_Data"))
        self.actionTest_Data = QtGui.QAction(TestWdw)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/data-accept-database-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTest_Data.setIcon(icon5)
        self.actionTest_Data.setObjectName(_fromUtf8("actionTest_Data"))
        self.actionExit = QtGui.QAction(TestWdw)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/exit-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon6)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(TestWdw)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icon-why-dark.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon7)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionAbout_Qt = QtGui.QAction(TestWdw)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/qt.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_Qt.setIcon(icon8)
        self.actionAbout_Qt.setObjectName(_fromUtf8("actionAbout_Qt"))
        self.menuMenu.addAction(self.actionTraining_Data)
        self.menuMenu.addAction(self.actionTest_Data)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(TestWdw)
        self.testDataTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TestWdw)

    def retranslateUi(self, TestWdw):
        TestWdw.setWindowTitle(_translate("TestWdw", "Text Dependent Speaker Verification - Testing", None))
        self.featureExtGroup.setTitle(_translate("TestWdw", "Feature Extraction", None))
        self.openAudioBtn.setText(_translate("TestWdw", "Open Audio File", None))
        self.extractSaveBtn.setText(_translate("TestWdw", "Extract Features", None))
        self.featureExtLbl.setText(_translate("TestWdw", "Features : ", None))
        self.metaGroup.setTitle(_translate("TestWdw", "Meta Info", None))
        self.fileLbl.setText(_translate("TestWdw", "File  ", None))
        self.samplesLbl.setText(_translate("TestWdw", "Samples ", None))
        self.fsLbl.setText(_translate("TestWdw", "FS ", None))
        self.audioFilenameLbl.setText(_translate("TestWdw", ":", None))
        self.sampleValLbl.setText(_translate("TestWdw", ":", None))
        self.fsValLbl.setText(_translate("TestWdw", ":", None))
        self.testDataGroup.setTitle(_translate("TestWdw", "Testing Data", None))
        self.testDataTab.setTabText(self.testDataTab.indexOf(self.origSignalTab), _translate("TestWdw", "Original Signal", None))
        self.testDataTab.setTabText(self.testDataTab.indexOf(self.framedSgnlTab), _translate("TestWdw", "Framed Signal", None))
        self.testDataTab.setTabText(self.testDataTab.indexOf(self.wdwSignalTab), _translate("TestWdw", "Windowed Signal", None))
        self.testDataTab.setTabText(self.testDataTab.indexOf(self.fftTab), _translate("TestWdw", "FFT", None))
        self.testDataTab.setTabText(self.testDataTab.indexOf(self.melWrapTab), _translate("TestWdw", "Mel Wrapping", None))
        self.testDataTab.setTabText(self.testDataTab.indexOf(self.mfccTab), _translate("TestWdw", "MFCC", None))
        self.paramsGroup.setTitle(_translate("TestWdw", "Params", None))
        self.learningRLbl.setText(_translate("TestWdw", "LR : ", None))
        self.learningRDecrLbl.setText(_translate("TestWdw", "LR decr : ", None))
        self.iterLbl.setText(_translate("TestWdw", "Max iter : ", None))
        self.learningRVal.setToolTip(_translate("TestWdw", "Learning Rate Value", None))
        self.learningRDecrVal.setToolTip(_translate("TestWdw", "Learning Rate Decrement Value", None))
        self.iterVal.setToolTip(_translate("TestWdw", "Maximum Iteration value", None))
        self.identifyBtn.setText(_translate("TestWdw", "Identify \n"
" && \n"
"Verify", None))
        self.wordVal.setText(_translate("TestWdw", ":", None))
        self.wordLbl.setText(_translate("TestWdw", "Word", None))
        self.speakerVal.setText(_translate("TestWdw", ":", None))
        self.speakerLbl.setText(_translate("TestWdw", "Speaker", None))
        self.resultLbl.setText(_translate("TestWdw", "TextLabel", None))
        self.menuMenu.setTitle(_translate("TestWdw", "Menu", None))
        self.menuAbout.setTitle(_translate("TestWdw", "Help", None))
        self.actionTraining_Data.setText(_translate("TestWdw", "Training Data", None))
        self.actionTest_Data.setText(_translate("TestWdw", "Testing Data", None))
        self.actionExit.setText(_translate("TestWdw", "Exit", None))
        self.actionAbout.setText(_translate("TestWdw", "About", None))
        self.actionAbout_Qt.setText(_translate("TestWdw", "About Qt", None))

from PyQt4 import phonon
import image_set_rc
