# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/ui_files/MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWdw(object):
    def setupUi(self, MainWdw):
        MainWdw.setObjectName(_fromUtf8("MainWdw"))
        MainWdw.resize(673, 458)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWdw.sizePolicy().hasHeightForWidth())
        MainWdw.setSizePolicy(sizePolicy)
        MainWdw.setMinimumSize(QtCore.QSize(673, 458))
        MainWdw.setMaximumSize(QtCore.QSize(672, 458))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/other-python-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWdw.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWdw)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.testingFrame = QtGui.QFrame(self.centralwidget)
        self.testingFrame.setGeometry(QtCore.QRect(0, 0, 661, 351))
        self.testingFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.testingFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.testingFrame.setObjectName(_fromUtf8("testingFrame"))
        self.trainingFrame = QtGui.QFrame(self.centralwidget)
        self.trainingFrame.setEnabled(True)
        self.trainingFrame.setGeometry(QtCore.QRect(0, 0, 671, 421))
        self.trainingFrame.setWhatsThis(_fromUtf8(""))
        self.trainingFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.trainingFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.trainingFrame.setObjectName(_fromUtf8("trainingFrame"))
        self.featureExtGroup = QtGui.QGroupBox(self.trainingFrame)
        self.featureExtGroup.setGeometry(QtCore.QRect(10, 10, 651, 181))
        self.featureExtGroup.setObjectName(_fromUtf8("featureExtGroup"))
        self.openAudioBtn = QtGui.QPushButton(self.featureExtGroup)
        self.openAudioBtn.setGeometry(QtCore.QRect(10, 22, 91, 31))
        self.openAudioBtn.setObjectName(_fromUtf8("openAudioBtn"))
        self.audioFilenameLbl = QtGui.QLabel(self.featureExtGroup)
        self.audioFilenameLbl.setGeometry(QtCore.QRect(110, 30, 151, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.audioFilenameLbl.setFont(font)
        self.audioFilenameLbl.setObjectName(_fromUtf8("audioFilenameLbl"))
        self.audioClassInput = QtGui.QLineEdit(self.featureExtGroup)
        self.audioClassInput.setGeometry(QtCore.QRect(390, 30, 113, 20))
        self.audioClassInput.setObjectName(_fromUtf8("audioClassInput"))
        self.audioClassLbl = QtGui.QLabel(self.featureExtGroup)
        self.audioClassLbl.setGeometry(QtCore.QRect(390, 10, 81, 16))
        self.audioClassLbl.setObjectName(_fromUtf8("audioClassLbl"))
        self.extractSaveBtn = QtGui.QPushButton(self.featureExtGroup)
        self.extractSaveBtn.setGeometry(QtCore.QRect(514, 10, 121, 41))
        self.extractSaveBtn.setObjectName(_fromUtf8("extractSaveBtn"))
        self.featuresTbl = QtGui.QTableWidget(self.featureExtGroup)
        self.featuresTbl.setGeometry(QtCore.QRect(260, 70, 381, 101))
        self.featuresTbl.setObjectName(_fromUtf8("featuresTbl"))
        self.featuresTbl.setColumnCount(0)
        self.featuresTbl.setRowCount(0)
        self.featureExtLbl = QtGui.QLabel(self.featureExtGroup)
        self.featureExtLbl.setGeometry(QtCore.QRect(260, 50, 81, 16))
        self.featureExtLbl.setObjectName(_fromUtf8("featureExtLbl"))
        self.seekSlider = phonon.Phonon.SeekSlider(self.featureExtGroup)
        self.seekSlider.setGeometry(QtCore.QRect(10, 90, 171, 22))
        self.seekSlider.setObjectName(_fromUtf8("seekSlider"))
        self.lcdNumber = QtGui.QLCDNumber(self.featureExtGroup)
        self.lcdNumber.setGeometry(QtCore.QRect(190, 90, 64, 23))
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.volumeSlider = phonon.Phonon.VolumeSlider(self.featureExtGroup)
        self.volumeSlider.setGeometry(QtCore.QRect(140, 140, 109, 22))
        self.volumeSlider.setObjectName(_fromUtf8("volumeSlider"))
        self.audioPlayBtn = QtGui.QPushButton(self.featureExtGroup)
        self.audioPlayBtn.setGeometry(QtCore.QRect(10, 130, 41, 41))
        self.audioPlayBtn.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/1461587404_play-arrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.audioPlayBtn.setIcon(icon1)
        self.audioPlayBtn.setIconSize(QtCore.QSize(16, 16))
        self.audioPlayBtn.setFlat(False)
        self.audioPlayBtn.setObjectName(_fromUtf8("audioPlayBtn"))
        self.audioPauseBtn = QtGui.QPushButton(self.featureExtGroup)
        self.audioPauseBtn.setGeometry(QtCore.QRect(50, 130, 41, 41))
        self.audioPauseBtn.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/1461587409_Pause_Icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.audioPauseBtn.setIcon(icon2)
        self.audioPauseBtn.setIconSize(QtCore.QSize(22, 22))
        self.audioPauseBtn.setObjectName(_fromUtf8("audioPauseBtn"))
        self.audioStopBtn = QtGui.QPushButton(self.featureExtGroup)
        self.audioStopBtn.setGeometry(QtCore.QRect(90, 130, 41, 41))
        self.audioStopBtn.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/1461587394_black_4_audio_stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.audioStopBtn.setIcon(icon3)
        self.audioStopBtn.setObjectName(_fromUtf8("audioStopBtn"))
        self.trainDataGroup = QtGui.QGroupBox(self.trainingFrame)
        self.trainDataGroup.setGeometry(QtCore.QRect(10, 200, 651, 211))
        self.trainDataGroup.setObjectName(_fromUtf8("trainDataGroup"))
        self.newWeightTbl = QtGui.QTableWidget(self.trainDataGroup)
        self.newWeightTbl.setGeometry(QtCore.QRect(225, 30, 421, 171))
        self.newWeightTbl.setObjectName(_fromUtf8("newWeightTbl"))
        self.newWeightTbl.setColumnCount(0)
        self.newWeightTbl.setRowCount(0)
        self.newWeightLbl = QtGui.QLabel(self.trainDataGroup)
        self.newWeightLbl.setGeometry(QtCore.QRect(570, 10, 71, 20))
        self.newWeightLbl.setObjectName(_fromUtf8("newWeightLbl"))
        self.trainDataBtn = QtGui.QPushButton(self.trainDataGroup)
        self.trainDataBtn.setGeometry(QtCore.QRect(10, 30, 75, 41))
        self.trainDataBtn.setObjectName(_fromUtf8("trainDataBtn"))
        self.trainProgress = QtGui.QProgressBar(self.trainDataGroup)
        self.trainProgress.setGeometry(QtCore.QRect(10, 180, 201, 23))
        self.trainProgress.setProperty("value", 24)
        self.trainProgress.setObjectName(_fromUtf8("trainProgress"))
        MainWdw.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWdw)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWdw.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWdw)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWdw.setStatusBar(self.statusbar)
        self.actionTraining_Data = QtGui.QAction(MainWdw)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/data-data-recovery-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTraining_Data.setIcon(icon4)
        self.actionTraining_Data.setObjectName(_fromUtf8("actionTraining_Data"))
        self.actionTest_Data = QtGui.QAction(MainWdw)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/data-accept-database-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTest_Data.setIcon(icon5)
        self.actionTest_Data.setObjectName(_fromUtf8("actionTest_Data"))
        self.actionExit = QtGui.QAction(MainWdw)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/exit-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon6)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(MainWdw)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icon-why-dark.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon7)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionAbout_Qt = QtGui.QAction(MainWdw)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/qt.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_Qt.setIcon(icon8)
        self.actionAbout_Qt.setObjectName(_fromUtf8("actionAbout_Qt"))
        self.menuMenu.addAction(self.actionTraining_Data)
        self.menuMenu.addAction(self.actionTest_Data)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWdw)
        QtCore.QMetaObject.connectSlotsByName(MainWdw)

    def retranslateUi(self, MainWdw):
        MainWdw.setWindowTitle(_translate("MainWdw", "Text Dependent Speaker Verification", None))
        self.featureExtGroup.setTitle(_translate("MainWdw", "Feature Extraction", None))
        self.openAudioBtn.setText(_translate("MainWdw", "Open Audio File", None))
        self.audioFilenameLbl.setText(_translate("MainWdw", "Audio name", None))
        self.audioClassLbl.setText(_translate("MainWdw", "Output Class :", None))
        self.extractSaveBtn.setText(_translate("MainWdw", "Extract && Save", None))
        self.featureExtLbl.setText(_translate("MainWdw", "Features : ", None))
        self.trainDataGroup.setTitle(_translate("MainWdw", "Training Data", None))
        self.newWeightLbl.setText(_translate("MainWdw", "New Weight : ", None))
        self.trainDataBtn.setText(_translate("MainWdw", "Train Data", None))
        self.menuMenu.setTitle(_translate("MainWdw", "Menu", None))
        self.menuAbout.setTitle(_translate("MainWdw", "Help", None))
        self.actionTraining_Data.setText(_translate("MainWdw", "Training Data", None))
        self.actionTest_Data.setText(_translate("MainWdw", "Test Data", None))
        self.actionExit.setText(_translate("MainWdw", "Exit", None))
        self.actionAbout.setText(_translate("MainWdw", "About", None))
        self.actionAbout_Qt.setText(_translate("MainWdw", "About Qt", None))

from PyQt4 import phonon
import image_set_rc
