# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/ui_files/MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWdw(object):
    def setupUi(self, MainWdw):
        MainWdw.setObjectName(_fromUtf8("MainWdw"))
        MainWdw.resize(673, 458)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWdw.sizePolicy().hasHeightForWidth())
        MainWdw.setSizePolicy(sizePolicy)
        MainWdw.setMinimumSize(QtCore.QSize(673, 458))
        MainWdw.setMaximumSize(QtCore.QSize(672, 458))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/other-python-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWdw.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWdw)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.testingFrame = QtGui.QFrame(self.centralwidget)
        self.testingFrame.setGeometry(QtCore.QRect(0, 0, 661, 351))
        self.testingFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.testingFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.testingFrame.setObjectName(_fromUtf8("testingFrame"))
        self.trainingFrame = QtGui.QFrame(self.centralwidget)
        self.trainingFrame.setEnabled(True)
        self.trainingFrame.setGeometry(QtCore.QRect(0, 0, 681, 421))
        self.trainingFrame.setWhatsThis(_fromUtf8(""))
        self.trainingFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.trainingFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.trainingFrame.setObjectName(_fromUtf8("trainingFrame"))
        self.featureExtGroup = QtGui.QGroupBox(self.trainingFrame)
        self.featureExtGroup.setGeometry(QtCore.QRect(10, 10, 651, 181))
        self.featureExtGroup.setObjectName(_fromUtf8("featureExtGroup"))
        self.openAudioBtn = QtGui.QPushButton(self.featureExtGroup)
        self.openAudioBtn.setGeometry(QtCore.QRect(10, 22, 91, 31))
        self.openAudioBtn.setObjectName(_fromUtf8("openAudioBtn"))
        self.audioClassInput = QtGui.QLineEdit(self.featureExtGroup)
        self.audioClassInput.setGeometry(QtCore.QRect(390, 30, 113, 20))
        self.audioClassInput.setObjectName(_fromUtf8("audioClassInput"))
        self.audioClassLbl = QtGui.QLabel(self.featureExtGroup)
        self.audioClassLbl.setGeometry(QtCore.QRect(390, 10, 81, 16))
        self.audioClassLbl.setObjectName(_fromUtf8("audioClassLbl"))
        self.extractSaveBtn = QtGui.QPushButton(self.featureExtGroup)
        self.extractSaveBtn.setGeometry(QtCore.QRect(514, 10, 121, 41))
        self.extractSaveBtn.setObjectName(_fromUtf8("extractSaveBtn"))
        self.featuresTbl = QtGui.QTableWidget(self.featureExtGroup)
        self.featuresTbl.setGeometry(QtCore.QRect(220, 80, 421, 91))
        self.featuresTbl.setObjectName(_fromUtf8("featuresTbl"))
        self.featuresTbl.setColumnCount(0)
        self.featuresTbl.setRowCount(0)
        self.featureExtLbl = QtGui.QLabel(self.featureExtGroup)
        self.featureExtLbl.setGeometry(QtCore.QRect(390, 60, 51, 16))
        self.featureExtLbl.setObjectName(_fromUtf8("featureExtLbl"))
        self.seekSlider = phonon.Phonon.SeekSlider(self.featureExtGroup)
        self.seekSlider.setGeometry(QtCore.QRect(120, 20, 161, 16))
        self.seekSlider.setObjectName(_fromUtf8("seekSlider"))
        self.lcdNumber = QtGui.QLCDNumber(self.featureExtGroup)
        self.lcdNumber.setGeometry(QtCore.QRect(290, 20, 64, 21))
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.volumeSlider = phonon.Phonon.VolumeSlider(self.featureExtGroup)
        self.volumeSlider.setGeometry(QtCore.QRect(240, 50, 109, 16))
        self.volumeSlider.setObjectName(_fromUtf8("volumeSlider"))
        self.audioPlayBtn = QtGui.QPushButton(self.featureExtGroup)
        self.audioPlayBtn.setGeometry(QtCore.QRect(120, 40, 41, 31))
        self.audioPlayBtn.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/1461587404_play-arrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.audioPlayBtn.setIcon(icon1)
        self.audioPlayBtn.setIconSize(QtCore.QSize(16, 16))
        self.audioPlayBtn.setFlat(False)
        self.audioPlayBtn.setObjectName(_fromUtf8("audioPlayBtn"))
        self.audioPauseBtn = QtGui.QPushButton(self.featureExtGroup)
        self.audioPauseBtn.setGeometry(QtCore.QRect(160, 40, 41, 31))
        self.audioPauseBtn.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/1461587409_Pause_Icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.audioPauseBtn.setIcon(icon2)
        self.audioPauseBtn.setIconSize(QtCore.QSize(22, 22))
        self.audioPauseBtn.setObjectName(_fromUtf8("audioPauseBtn"))
        self.audioStopBtn = QtGui.QPushButton(self.featureExtGroup)
        self.audioStopBtn.setGeometry(QtCore.QRect(200, 40, 41, 31))
        self.audioStopBtn.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/1461587394_black_4_audio_stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.audioStopBtn.setIcon(icon3)
        self.audioStopBtn.setObjectName(_fromUtf8("audioStopBtn"))
        self.metaGroup = QtGui.QGroupBox(self.featureExtGroup)
        self.metaGroup.setGeometry(QtCore.QRect(10, 80, 201, 91))
        self.metaGroup.setObjectName(_fromUtf8("metaGroup"))
        self.fileLbl = QtGui.QLabel(self.metaGroup)
        self.fileLbl.setGeometry(QtCore.QRect(10, 20, 31, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fileLbl.setFont(font)
        self.fileLbl.setObjectName(_fromUtf8("fileLbl"))
        self.samplesLbl = QtGui.QLabel(self.metaGroup)
        self.samplesLbl.setGeometry(QtCore.QRect(10, 40, 51, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.samplesLbl.setFont(font)
        self.samplesLbl.setObjectName(_fromUtf8("samplesLbl"))
        self.fsLbl = QtGui.QLabel(self.metaGroup)
        self.fsLbl.setGeometry(QtCore.QRect(10, 60, 21, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fsLbl.setFont(font)
        self.fsLbl.setObjectName(_fromUtf8("fsLbl"))
        self.audioFilenameLbl = QtGui.QLabel(self.metaGroup)
        self.audioFilenameLbl.setGeometry(QtCore.QRect(60, 20, 131, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.audioFilenameLbl.setFont(font)
        self.audioFilenameLbl.setObjectName(_fromUtf8("audioFilenameLbl"))
        self.sampleValLbl = QtGui.QLabel(self.metaGroup)
        self.sampleValLbl.setGeometry(QtCore.QRect(60, 40, 131, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sampleValLbl.setFont(font)
        self.sampleValLbl.setObjectName(_fromUtf8("sampleValLbl"))
        self.fsValLbl = QtGui.QLabel(self.metaGroup)
        self.fsValLbl.setGeometry(QtCore.QRect(60, 60, 131, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fsValLbl.setFont(font)
        self.fsValLbl.setObjectName(_fromUtf8("fsValLbl"))
        self.trainDataGroup = QtGui.QGroupBox(self.trainingFrame)
        self.trainDataGroup.setGeometry(QtCore.QRect(10, 200, 651, 211))
        self.trainDataGroup.setObjectName(_fromUtf8("trainDataGroup"))
        self.newWeightTbl = QtGui.QTableWidget(self.trainDataGroup)
        self.newWeightTbl.setGeometry(QtCore.QRect(225, 30, 421, 171))
        self.newWeightTbl.setObjectName(_fromUtf8("newWeightTbl"))
        self.newWeightTbl.setColumnCount(0)
        self.newWeightTbl.setRowCount(0)
        self.newWeightLbl = QtGui.QLabel(self.trainDataGroup)
        self.newWeightLbl.setGeometry(QtCore.QRect(580, 10, 71, 20))
        self.newWeightLbl.setObjectName(_fromUtf8("newWeightLbl"))
        self.trainDataBtn = QtGui.QPushButton(self.trainDataGroup)
        self.trainDataBtn.setGeometry(QtCore.QRect(10, 130, 75, 41))
        self.trainDataBtn.setObjectName(_fromUtf8("trainDataBtn"))
        self.trainProgress = QtGui.QProgressBar(self.trainDataGroup)
        self.trainProgress.setGeometry(QtCore.QRect(10, 180, 201, 23))
        self.trainProgress.setProperty("value", 0)
        self.trainProgress.setTextVisible(False)
        self.trainProgress.setObjectName(_fromUtf8("trainProgress"))
        self.paramsGroup = QtGui.QGroupBox(self.trainDataGroup)
        self.paramsGroup.setGeometry(QtCore.QRect(10, 20, 161, 101))
        self.paramsGroup.setObjectName(_fromUtf8("paramsGroup"))
        self.learningRLbl = QtGui.QLabel(self.paramsGroup)
        self.learningRLbl.setGeometry(QtCore.QRect(10, 20, 31, 16))
        self.learningRLbl.setObjectName(_fromUtf8("learningRLbl"))
        self.learningRDecrLbl = QtGui.QLabel(self.paramsGroup)
        self.learningRDecrLbl.setGeometry(QtCore.QRect(10, 40, 51, 16))
        self.learningRDecrLbl.setObjectName(_fromUtf8("learningRDecrLbl"))
        self.iterLbl = QtGui.QLabel(self.paramsGroup)
        self.iterLbl.setGeometry(QtCore.QRect(10, 60, 51, 16))
        self.iterLbl.setObjectName(_fromUtf8("iterLbl"))
        self.learningRVal = QtGui.QDoubleSpinBox(self.paramsGroup)
        self.learningRVal.setGeometry(QtCore.QRect(70, 20, 62, 16))
        self.learningRVal.setFrame(False)
        self.learningRVal.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.learningRVal.setDecimals(3)
        self.learningRVal.setMaximum(9999.999)
        self.learningRVal.setSingleStep(0.01)
        self.learningRVal.setProperty("value", 0.05)
        self.learningRVal.setObjectName(_fromUtf8("learningRVal"))
        self.learningRDecrVal = QtGui.QDoubleSpinBox(self.paramsGroup)
        self.learningRDecrVal.setGeometry(QtCore.QRect(70, 40, 62, 16))
        self.learningRDecrVal.setFrame(False)
        self.learningRDecrVal.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.learningRDecrVal.setDecimals(3)
        self.learningRDecrVal.setMaximum(9999.999)
        self.learningRDecrVal.setSingleStep(0.001)
        self.learningRDecrVal.setProperty("value", 0.977)
        self.learningRDecrVal.setObjectName(_fromUtf8("learningRDecrVal"))
        self.iterVal = QtGui.QSpinBox(self.paramsGroup)
        self.iterVal.setGeometry(QtCore.QRect(70, 60, 61, 16))
        self.iterVal.setFrame(False)
        self.iterVal.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.iterVal.setMaximum(9999)
        self.iterVal.setProperty("value", 1)
        self.iterVal.setObjectName(_fromUtf8("iterVal"))
        MainWdw.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWdw)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWdw.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWdw)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWdw.setStatusBar(self.statusbar)
        self.actionTraining_Data = QtGui.QAction(MainWdw)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/data-data-recovery-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTraining_Data.setIcon(icon4)
        self.actionTraining_Data.setObjectName(_fromUtf8("actionTraining_Data"))
        self.actionTest_Data = QtGui.QAction(MainWdw)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/data-accept-database-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTest_Data.setIcon(icon5)
        self.actionTest_Data.setObjectName(_fromUtf8("actionTest_Data"))
        self.actionExit = QtGui.QAction(MainWdw)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/exit-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon6)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(MainWdw)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icon-why-dark.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon7)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionAbout_Qt = QtGui.QAction(MainWdw)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/qt.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_Qt.setIcon(icon8)
        self.actionAbout_Qt.setObjectName(_fromUtf8("actionAbout_Qt"))
        self.actionBatch_Feature_Extraction = QtGui.QAction(MainWdw)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/1462517805_FILE - BATCH.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBatch_Feature_Extraction.setIcon(icon9)
        self.actionBatch_Feature_Extraction.setObjectName(_fromUtf8("actionBatch_Feature_Extraction"))
        self.menuMenu.addAction(self.actionBatch_Feature_Extraction)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionTraining_Data)
        self.menuMenu.addAction(self.actionTest_Data)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWdw)
        QtCore.QMetaObject.connectSlotsByName(MainWdw)

    def retranslateUi(self, MainWdw):
        MainWdw.setWindowTitle(_translate("MainWdw", "Text Dependent Speaker Verification - Training", None))
        self.featureExtGroup.setTitle(_translate("MainWdw", "Feature Extraction", None))
        self.openAudioBtn.setText(_translate("MainWdw", "Open Audio File", None))
        self.audioClassLbl.setText(_translate("MainWdw", "Output Class :", None))
        self.extractSaveBtn.setText(_translate("MainWdw", "Extract && Save", None))
        self.featureExtLbl.setText(_translate("MainWdw", "Features : ", None))
        self.metaGroup.setTitle(_translate("MainWdw", "Meta Info", None))
        self.fileLbl.setText(_translate("MainWdw", "File  ", None))
        self.samplesLbl.setText(_translate("MainWdw", "Samples ", None))
        self.fsLbl.setText(_translate("MainWdw", "FS ", None))
        self.audioFilenameLbl.setText(_translate("MainWdw", ":", None))
        self.sampleValLbl.setText(_translate("MainWdw", ":", None))
        self.fsValLbl.setText(_translate("MainWdw", ":", None))
        self.trainDataGroup.setTitle(_translate("MainWdw", "Training Data", None))
        self.newWeightLbl.setText(_translate("MainWdw", "New Weight : ", None))
        self.trainDataBtn.setText(_translate("MainWdw", "Train Data", None))
        self.paramsGroup.setTitle(_translate("MainWdw", "Params", None))
        self.learningRLbl.setText(_translate("MainWdw", "LR : ", None))
        self.learningRDecrLbl.setText(_translate("MainWdw", "LR decr : ", None))
        self.iterLbl.setText(_translate("MainWdw", "Max iter : ", None))
        self.learningRVal.setToolTip(_translate("MainWdw", "Learning Rate Value", None))
        self.learningRDecrVal.setToolTip(_translate("MainWdw", "Learning Rate Decrement Value", None))
        self.iterVal.setToolTip(_translate("MainWdw", "Maximum Iteration value", None))
        self.menuMenu.setTitle(_translate("MainWdw", "Menu", None))
        self.menuAbout.setTitle(_translate("MainWdw", "Help", None))
        self.actionTraining_Data.setText(_translate("MainWdw", "Training Data", None))
        self.actionTest_Data.setText(_translate("MainWdw", "Testing Data", None))
        self.actionExit.setText(_translate("MainWdw", "Exit", None))
        self.actionAbout.setText(_translate("MainWdw", "About", None))
        self.actionAbout_Qt.setText(_translate("MainWdw", "About Qt", None))
        self.actionBatch_Feature_Extraction.setText(_translate("MainWdw", "Batch Feature Extraction", None))

from PyQt4 import phonon
import image_set_rc
